### ISSUE TITLE
problem with running

### ISSUE THREAD

**Issue by fabian93** [iTommix/pyCAR#1]
amixer: mixer attach default error: no such file or directory

**Comment by St3v390** [comment]
HI fabian,

this "error" is caused by blocking snd_bcm2835 in "part1.sh" line 35.
You can manaully delete the line "blacklist snd_bcm2835" in /etc/modprobe.d/raspi-blacklist.conf

Also you can connect an external Soundcard (via USB) to solve this problem.
I don't think that this is an error.

**Comment by Fernando-olm** [comment]
Indeed, 
Thats not an error, you should look for the reason why the message is being raised. Maybe the sound card is not attached, with some driver problem or just without a "mixer" role in ".asound.rc".

What happened to me and my sound card, I needed to fix in the code though:
In the first lines of "main.py" code, I needed to give up using alsaaudio.pcms(), instead, I'm using:
`import alsaaudio
alsaaudio.cards()`

Then, where it calls for alsaaudio.Mixer(), for example in the setVolume method, I needed to change to:
`mixer = alsaaudio.Mixer(control = 'Speaker', cardindex = 1)`

Another problem I've got was with the "mainVolume" setting, my audio board had only 2 channels, then I needed to change it from: 
`"mainVolume"        : [30,30,30,30],`
to:
`"mainVolume"        : [30,30],`

**Comment by iTommix** [comment]
This issue is related to an old release of pyCAR. Please try the actual version.
